[package]
name = "relay-rs"
description = "A no nonsense ordered job runner with configurable backends for optionally persisted data"
version = "0.1.0"
edition = "2021"
authors = ["Dean Karn <dean.karn@gmail.com>"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/rust-playground/relay-rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = { version = "4.0.0-beta.19", default-features = false, features = ["compress-gzip", "rustls"] }
anyhow = "1.0.52"
async-stream = "0.3.2"
async-trait = "0.1.52"
chrono = { version = "0.4.19", features = ["serde"] }
clap = { version = "3.0.5", features = ["derive", "env"] }
log = "0.4.14"
serde = { version = "1.0.133", features = ["derive"] }
serde_json = { version = "1.0.74", features = ["raw_value"] }
thiserror = "1.0.30"
tokio = { version = "1.15.0", features = ["rt-multi-thread", "net", "time","macros"] }
tokio-stream = "0.1.8"
tracing = "0.1.29"
tracing-subscriber = { version = "0.3.5", features = ["env-filter"] }
ahash = "0.7.6"
metrics = "0.17.1"
metrics-util = "0.10.2"

[features]
default = []
sqlite_backing = ["sqlx","sqlx/sqlite", "sqlx/chrono","sqlx/runtime-tokio-rustls", "sqlx/all-types", "sqlx/migrate"]
postgres_backing = ["sqlx","sqlx/postgres", "sqlx/chrono","sqlx/runtime-tokio-rustls", "sqlx/all-types", "sqlx/migrate"]
redis_backing = ["redis", "redis/r2d2", "redis/aio", "redis/tokio-comp", "redis/connection-manager", "redis/tokio-native-tls-comp"]
dynamodb_backing = ["aws-sdk-dynamodb", "aws-sdk-dynamodb/rustls", "aws-config"]
prometheus_metrics = ["metrics-exporter-prometheus"]

[dependencies.metrics-exporter-prometheus]
version = "0.7.0"
optional = true

[dependencies.redis]
version = "0.21.4"
optional = true

[dependencies.sqlx]
 version = "0.5.10"
optional = true

[dependencies.aws-sdk-dynamodb]
version = "0.4.0"
optional = true

[dependencies.aws-config]
version = "0.4.0"
optional = true

[package.metadata.docs.rs]
all-features = true

[package.metadata.playground]
all-features = true
