name: Lint & Test
on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo test --all-features --all-targets --workspace --exclude=relay-bin

  build:
    strategy:
      matrix:
        platform: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo check --all-features --all-targets --workspace --exclude=relay-bin
      - run: cargo check -p relay-bin --all-targets --features=metrics-prometheus,backing-redis
      - run: cargo check -p relay-bin --all-targets --features=metrics-prometheus,backing-postgres
      - run: cargo check -p relay-bin --all-targets --features=metrics-prometheus,backing-sqlite
      - run: cargo check -p relay-bin --all-targets --features=metrics-prometheus,backing-dynamodb

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@clippy
      - run: cargo clippy --all-features --tests --workspace --exclude relay-bin -- -Dclippy::all -Dclippy::pedantic
      - run: cargo clippy -p relay-bin --tests --features=metrics-prometheus,backing-redis -- -Dclippy::all -Dclippy::pedantic
      - run: cargo clippy -p relay-bin --tests --features=metrics-prometheus,backing-postgres -- -Dclippy::all -Dclippy::pedantic
      - run: cargo clippy -p relay-bin --tests --features=metrics-prometheus,backing-sqlite -- -Dclippy::all -Dclippy::pedantic
      - run: cargo clippy -p relay-bin --tests --features=metrics-prometheus,backing-dynamodb -- -Dclippy::all -Dclippy::pedantic
