name: Lint & Test
on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo test --features=prometheus_metrics
      - run: cargo test --features=prometheus_metrics,sqlite_backing
      - run: cargo test --features=prometheus_metrics,postgres_backing
      - run: cargo test --features=prometheus_metrics,redis_backing
      - run: cargo test --features=prometheus_metrics,dynamodb_backing

  build:
    strategy:
      matrix:
        platform: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo check --features=prometheus_metrics
      - run: cargo check --features=prometheus_metrics,sqlite_backing
      - run: cargo check --features=prometheus_metrics,postgres_backing
      - run: cargo check --features=prometheus_metrics,redis_backing
      - run: cargo check --features=prometheus_metrics,dynamodb_backing

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@clippy
      - run: cargo clippy --features=prometheus_metrics --tests -- -Dclippy::all -Dclippy::pedantic
      - run: cargo clippy --features=prometheus_metrics,redis_backing --tests -- -Dclippy::all -Dclippy::pedantic
      - run: cargo clippy --features=prometheus_metrics,sqlite_backing --tests -- -Dclippy::all -Dclippy::pedantic
      - run: cargo clippy --features=prometheus_metrics,postgres_backing --tests -- -Dclippy::all -Dclippy::pedantic
      - run: cargo clippy --features=prometheus_metrics,dynamodb_backing --tests -- -Dclippy::all -Dclippy::pedantic
